services:
  tts:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.tts
    image: tts
    container_name: tts-server
    ports:
      - "5002:5002"
    volumes:
      - ./tmp/assets:/root/assets
      - ./tmp/tts_models:/root/.local/share/tts/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Use all available GPUs
              capabilities: [ gpu ]  # Required for NVIDIA
  
  bot:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.bot
    image: discordttsbot
    container_name: discord-tts-bot
    volumes:
      - ./tmp/assets:/app/tmp/assets
      - ./config.json:/app/config.json