FROM golang:1.24.5 AS builder

RUN apt-get update && apt-get install -y \
    pkg-config \
    libopus-dev \
    libopusfile-dev \
    libogg-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build \
    -ldflags="-extldflags '-static -lopusfile -lopus -logg -lm'" \
    -tags static \
    -o /app/main .

ENTRYPOINT ["/app/main"]