FROM ubuntu:24.04

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y --no-install-recommends curl gcc g++ ca-certificates && \
rm -rf /var/lib/apt/lists/*

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

RUN uv python install --default 3.12
RUN uv venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN uv pip install coqui-tts[server]

WORKDIR /root

CMD ["tts-server", "--model_name", "tts_models/multilingual/multi-dataset/xtts_v2"]